server:
  port: 18080
net.marioplus.domain-dns-auto-refresh:
  cron: 0 * * * * ?
  dns-accounts:
    - access-key-id: xxx
      access-Key-secret: xxx
      endpoint: alidns.cn-shenzhen.aliyuncs.com
      records:
        - domain-name: xxx.com
          record-id: xxx
          RR: mc
          type: A

logging.file.path: ./logs

management:
  endpoint.shutdown.enabled: true
  endpoints.web.exposure.include: shutdown
